version: "3.7"

services:
  db:
    container_name: audio_shorts_api_database
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
  backend:
    container_name: audio_shorts_api_backend
    build: .
    command: ["go", "run", "cmd/main.go"]
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  data:

